package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strings"
	"time"

	"kt-ai-studio/internal/db"
	"kt-ai-studio/internal/models"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

func normalizeAutoGenerateTagIDs(ids []uint) []uint {
	if len(ids) == 0 {
		return []uint{}
	}
	seen := make(map[uint]struct{}, len(ids))
	normalized := make([]uint, 0, len(ids))
	for _, id := range ids {
		if id == 0 {
			continue
		}
		if _, exists := seen[id]; exists {
			continue
		}
		seen[id] = struct{}{}
		normalized = append(normalized, id)
	}
	sort.Slice(normalized, func(i, j int) bool {
		return normalized[i] < normalized[j]
	})
	return normalized
}

func encodeAutoGenerateTagIDs(ids []uint) string {
	normalized := normalizeAutoGenerateTagIDs(ids)
	if len(normalized) == 0 {
		return ""
	}
	encoded, err := json.Marshal(normalized)
	if err != nil {
		return ""
	}
	return string(encoded)
}

func parseAutoGenerateTagIDs(raw string) []uint {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return []uint{}
	}
	var ids []uint
	if err := json.Unmarshal([]byte(raw), &ids); err != nil {
		return []uint{}
	}
	return normalizeAutoGenerateTagIDs(ids)
}

func applyAutoGenerateDraftTagIDs(draft *models.AutoGenerateDraft) {
	if draft == nil {
		return
	}
	draft.TagIDs = parseAutoGenerateTagIDs(draft.TagIDsJSON)
}

func listSelectedAutoGenerateTags(ids []uint) ([]models.AutoGenerateTag, error) {
	normalized := normalizeAutoGenerateTagIDs(ids)
	if len(normalized) == 0 {
		return []models.AutoGenerateTag{}, nil
	}
	var tags []models.AutoGenerateTag
	if err := db.DB.
		Where("id IN ?", normalized).
		Order("sort_order ASC, id ASC").
		Find(&tags).Error; err != nil {
		return nil, err
	}
	return tags, nil
}

// ListAutoGenerateTags retrieves all auto-generate prompt tags.
func ListAutoGenerateTags(c *gin.Context) {
	var tags []models.AutoGenerateTag
	if err := db.DB.Order("sort_order ASC, id ASC").Find(&tags).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to fetch auto-generate tags"})
		return
	}
	c.JSON(http.StatusOK, tags)
}

// AddAutoGenerateTag creates a new auto-generate prompt tag.
func AddAutoGenerateTag(c *gin.Context) {
	var tag models.AutoGenerateTag
	if err := c.ShouldBindJSON(&tag); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	tag.Name = strings.TrimSpace(tag.Name)
	tag.Slug = strings.TrimSpace(tag.Slug)
	tag.Description = strings.TrimSpace(tag.Description)
	tag.Rules = strings.TrimSpace(tag.Rules)
	if tag.Name == "" || tag.Description == "" || tag.Rules == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "name, description and rules are required"})
		return
	}
	if tag.Slug == "" {
		tag.Slug = sanitizeAutoGenerateTagSlug(tag.Name)
	}
	tag.CreatedAt = time.Now()
	tag.UpdatedAt = time.Now()
	if err := db.DB.Create(&tag).Error; err != nil {
		Log(LogLevelError, "创建自动剧情标签失败", err.Error())
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create auto-generate tag"})
		return
	}
	Log(LogLevelInfo, "创建自动剧情标签", fmt.Sprintf("创建了新标签: %s", tag.Name))
	c.JSON(http.StatusCreated, tag)
}

// UpdateAutoGenerateTag updates an existing auto-generate prompt tag.
func UpdateAutoGenerateTag(c *gin.Context) {
	id := c.Param("id")
	var tag models.AutoGenerateTag
	if err := db.DB.First(&tag, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Auto-generate tag not found"})
		return
	}

	var updateData models.AutoGenerateTag
	if err := c.ShouldBindJSON(&updateData); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	tag.Name = strings.TrimSpace(updateData.Name)
	tag.Description = strings.TrimSpace(updateData.Description)
	tag.Rules = strings.TrimSpace(updateData.Rules)
	tag.SortOrder = updateData.SortOrder
	slug := strings.TrimSpace(updateData.Slug)
	if slug == "" {
		slug = sanitizeAutoGenerateTagSlug(tag.Name)
	}
	tag.Slug = slug
	tag.UpdatedAt = time.Now()

	if tag.Name == "" || tag.Description == "" || tag.Rules == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "name, description and rules are required"})
		return
	}

	if err := db.DB.Save(&tag).Error; err != nil {
		Log(LogLevelError, "更新自动剧情标签失败", err.Error())
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update auto-generate tag"})
		return
	}

	Log(LogLevelInfo, "更新自动剧情标签", fmt.Sprintf("更新了标签: %s", tag.Name))
	c.JSON(http.StatusOK, tag)
}

// DeleteAutoGenerateTag deletes an auto-generate prompt tag.
func DeleteAutoGenerateTag(c *gin.Context) {
	id := c.Param("id")
	if err := db.DB.Delete(&models.AutoGenerateTag{}, id).Error; err != nil {
		Log(LogLevelError, "删除自动剧情标签失败", err.Error())
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to delete auto-generate tag"})
		return
	}
	Log(LogLevelInfo, "删除自动剧情标签", fmt.Sprintf("删除标签 ID: %s", id))
	c.JSON(http.StatusOK, gin.H{"message": "Auto-generate tag deleted successfully"})
}

func sanitizeAutoGenerateTagSlug(name string) string {
	replacer := strings.NewReplacer(
		" ", "-",
		"·", "-",
		"—", "-",
		"_", "-",
		"/", "-",
		"\\", "-",
	)
	slug := strings.ToLower(strings.Trim(replacer.Replace(strings.TrimSpace(name)), "-"))
	if slug == "" {
		return "tag"
	}
	return slug
}

// InitDefaultAutoGenerateTags upserts default prompt tags.
func InitDefaultAutoGenerateTags() {
	defaultTags := []models.AutoGenerateTag{
		{
			Name:        "古代场景",
			Slug:        "ancient-scene",
			Description: "适用于皇宫、殿堂、宗门、客栈、驿站、古代街巷、古代居所等古代空间。",
			SortOrder:   10,
			Rules: strings.TrimSpace(`- 当前故事涉及中国古代或架空古代空间时，必须先锁定时代语境：屋檐形制、门窗结构、木梁、石阶、屏风、帷幔、桌案、灯笼、香炉、栏杆、瓦面、地砖与器物样式都要符合古代环境，禁止混入现代家具、现代灯具、现代玻璃办公感、现代门把手或模糊的通用现代室内。
- 若镜头发生在皇宫、大殿、议事厅、宗门主殿、祠堂、山门、古宅正厅等层级空间，优先建立台阶、柱位、门框、屏风、主位坐席、进深和高低位，让观众一眼看出空间等级关系与尊卑关系；不要把高位空间拍成没有柱网、没有门框、没有主位参照的空房间。
- 船舱、客栈、古宅卧房、驿站、街巷、庭院这类古代空间，也必须保持器物与建筑语境统一，例如木格窗、灯笼、桌案、布帘、床榻、木门、栅栏、石板路、木栏与古代材质，不要写成模糊的通用室内。
- 同一处古代地点在连续镜头中，必须持续继承同一组空间骨架和器物锚点，例如柱子数量与方向、台阶上下关系、屏风位置、门框开口、船舷高度、甲板栏杆、桌案位置、灯笼位置、窗格样式；不要让同一地点在后续镜头里忽然换结构、换材质、换朝向。
- 若古代场景中存在明确的礼制站位、朝堂班列、门侧守位、宴席座次、山门迎候位、船头船尾分工位，就必须保持这套空间关系，不要让人物无缘由跨越主位、乱换前后层次或脱离原本礼制秩序。
- 古代场景里的天气、时段与材质反应也必须统一：夜间主要靠灯笼、烛火、月光、檐下漏光、走廊暗灯或冷月反光；雨夜要让瓦面、石阶、木栏和衣摆出现合理湿度；雪景要让屋檐、台阶、甲板、栏杆和衣角保持一致积雪或湿痕，不要一镜有雪一镜无雪。 `),
		},
		{
			Name:        "现代场景",
			Slug:        "modern-scene",
			Description: "适用于办公室、住宅、医院、校园、商场、街道等现代题材场景。",
			SortOrder:   20,
			Rules: strings.TrimSpace(`- 当前故事涉及现代空间时，必须优先锁定现代环境识别点：玻璃、金属、混凝土、办公桌、显示器、病床、楼道扶手、现代门窗、现代灯具、城市窗景、车辆结构、瓷砖、沙发、柜体、门牌、墙面开关和现代材质都要符合现代语境，不要混入古代器物或模糊的通用空间。
- 办公室、会议室、病房、走廊、出租屋、厨房、学校教室、商场、街道等现代场景，优先用门、窗、桌、床、灯、显示器、通道、柜体、扶手和街景关系建立空间，不要只写“室内”“办公室氛围”“现代感很强”这类抽象概括。
- 若镜头发生在办公室、病房、教室、会议室、酒店房间、住宅客厅、出租屋卧室、现代车内这类固定重复地点，必须持续继承同一组空间锚点，例如门的位置、窗的位置、桌床柜关系、主灯方向、显示器位置、病床护栏、沙发朝向、车窗车门方向；不要让同一地点在后续镜头里忽然变成另一套结构。
- 现代场景中的设备和载体要有明确附着关系：显示器要属于某张桌、病床要在病房结构内、门禁要在门框边、车内扶手和方向盘要在合理位置；不要把局部特写写成漂浮静物。
- 若现代场景包含明显的公共空间秩序，例如医院走廊、办公室工位、会议室座次、教室座位、车内座位、商场通道、站台边界，就必须持续保持这套空间逻辑，不要让人物无缘由换到不合理位置。
- 现代夜景、雨夜、霓虹、办公室顶灯、病房白灯、楼道应急灯等光源也必须持续统一；不要一镜冷白医院灯，下一镜忽然变成古风暖灯或来源不明的戏剧化顶光。 `),
		},
		{
			Name:        "狭窄空间",
			Slug:        "tight-space",
			Description: "适用于车内、电梯、门口、病房玄关、出租屋角落等狭窄或封闭空间。",
			SortOrder:   30,
			Rules: strings.TrimSpace(`- 当前镜头若发生在车内、电梯、病房门口、楼梯转角、出租屋角落、狭长走廊、卫生间、储物间或任何狭窄空间，单镜只保留 1 个清晰主位人物，必要时最多再带 1 个主要联动人物，其余人物只做背景轮廓或弱反应。
- 狭窄空间不要依赖大幅环绕、激烈平移或多人横向并排塞满画面；优先使用前后层次、过肩、门框遮挡、局部近景和中近景，把空间压迫感建立清楚。
- 在狭窄空间里，如果动作需要明显转身、跨步、倒地、近身冲撞、掐住、推门、按住、递交、接住或兵器接触，首帧必须先把动作起点、接触点和身体可见范围建立清楚；做不到就拆镜。
- 狭窄空间中的多人镜头必须优先保住人物和门框、床沿、墙角、扶手、桌边、驾驶区、座椅、走道这些边界关系；不要让人物身体穿墙、穿门、穿座椅，也不要让两个人在没有空间的情况下完成完整大动作。
- 若画面是门口、玄关、车门边、床边、楼梯转角、电梯门内外这种边界型空间，必须先建立谁在门内、谁在门外、谁贴墙、谁挡路、谁有退路；做不到就不要强压复杂对峙或接触动作。
- 狭窄空间镜头默认减少背景杂物和次要人物，不要为了信息量把柜子、椅子、门、床、设备、行李、人同时塞满画面；先保证动作起点、接触点和通行路径可见。 `),
		},
		{
			Name:        "古代打斗",
			Slug:        "ancient-combat",
			Description: "适用于中国古装武打、兵器对打、暗器、轻功腾空、船上打斗等动作场景。",
			SortOrder:   40,
			Rules: strings.TrimSpace(`- 中国古装打斗、多人兵器动作、长发宽袖动作、群战、多人同时中招都属于高负载内容。默认优先降复杂度：单镜只保留 1 个主攻击事件，最多只保留 1 到 2 个清楚可见的受击者，其余人只做背景威胁或弱反应。
- 不要在一个动作镜头里同时要求“多人围攻、主角出招、多人中招、多人倒地、大幅运镜、复杂对白”。只要动作事件超过一个主事件，就拆成相邻镜头顺着打。
- 暗器、银针、飞刀、箭矢、投掷物这类镜头，必须尽量让飞行方向、目标位置、命中部位和受击反应在镜头内形成闭环。不要只写“手一弹，然后几个人倒下”，也不要只写“暗器如雨”“银针成束”而不给出清楚命中对象。
- 对打镜头优先写“谁在动、打向哪里、目标如何反应”，不要优先写抽象武打效果词。不要写“招式凌厉”“打斗激烈”“压迫感强”“张力拉满”；要写成具体的挥砍、格挡、刺入、后退、踉跄、脱手、跪倒、捂伤处、呼吸变化和视线变化。
- 若一个动作镜头的主要结果只是为了交代“敌人被击退”“受害者中招”“武器脱手”“毒雾被克制”，就优先把这一个结果拍清楚，不要贪多。动作镜头越单一，模型越稳定。
- 多人打斗时，背景人物只能承担追击、围拢、逼近、后退、惊停或弱攻击等背景动作，不要让所有人同时做完整可读动作。真正的主动作只给当前主位人物和当前受击人物。
- 对刀、剑、枪、棍、弯刀、匕首、银针、箭矢和其他手持武器，先追踪其物理状态：当前由谁持有、拿在哪只手、是否出鞘、是否已发出、是否仍握在手里、是否别在腰后、是否掉到地面、是否留在对手身上。后续镜头若没有明确动作交代，不要无缘由换手、换位置、消失又出现、凭空多出第二把；脚本没写双持时，不要主动补成双持。
- 关键道具若需要在打斗、奔逃、跳跃或近身搏杀中继续跟随人物，就必须先改写成物理上合理的携带状态，例如贴胸压住、塞入衣襟内侧、挂在腰侧、握在非主用手且手臂姿势能成立；一旦建立这种携带方式，后续镜头必须继续继承，直到脚本明确写出它被拿出、被交换、被丢失、被拼合或被激活。
- 多人动作镜头里，承担主动作、主受击、主格挡或关键道具变化的那个人，必须始终保持为当前画面最清楚、最容易识别的主位人物。不要让同场其他敌人、路人或同色服装人物抢走主位；若当前画面无法同时看清主位人物和关键对手，就拆镜。
- 对蒙面、披风遮脸、兜帽遮面、半遮面等容易歧义的外观词，必须改写成符合当前动作的具体可见形式；若脚本没有明确写“遮住双眼”或“蒙眼”，就不要把它画成会妨碍视线和动作的蒙眼状态。
- 当同一镜头里同时出现两名或以上同性别、同年代、同题材服装的人物，且其中有人承担打斗、对峙、受击或关键道具变化时，必须为每个正在参与主动作的人重复当前镜头专属的可见区分锚点，例如衣服主色、外袍层次、脸部疤痕、持械手、站位方向；不要只写“中年男性”“青年男子”后就让模型自己猜谁是谁。
- 若脚本明确写的是单把刀、单把剑、单支枪、单根棍、单柄匕首或单件可见武器，就必须保持单数，不要凭空多出第二把同类武器。
- 对长剑、长枪、长棍、长柄武器、细长暗器束和其他细长兵器，只要后续镜头运动、人物动作或构图变化会暴露出更多长度，首帧图就必须先建立足够的可见长度与朝向；不要让镜头在后续运动里替模型脑补隐藏长度，导致武器被无缘由拉长到不合理尺寸。
- 若动作链同时包含起手、释放、飞行、命中、结果反应中的三类或更多，应主动拆成准备镜、释放镜、命中镜、结果镜或反应镜；不要让同一镜头同时承担人物起势、武器飞行、目标受击和流血倒地整条因果链。
- 对腾空、跳跃、飞扑、抛掷、暗器出手、远距离刺击和从画外飞来的武器，不要让同一镜头同时承担“人物起势、道具飞行、目标受击、流血倒地”整条因果链。若当前镜头先拍起手或腾空，就把命中与结果拆到后续镜头；若当前镜头先拍受击结果，就让首帧先建立受击者和来袭方向。
- 若当前镜头的关键互动依赖两方或多方才能成立，例如挥砍、格挡、刺入、击中、掐住、按住、拉住、推开、护人、挡招或兵器贴身对峙，首帧图里就必须先把关键参与者、接触部位和接触点建立出来；若画面里没有第二个关键人物，就不要让视频靠画外人物补完整个动作。
- 船上打斗、桥上打斗、山路边缘、楼梯高低位、屋顶边缘、悬崖边、门槛内外这些带明显空间危险的古装动作镜头，必须先把地面方向、边缘位置、栏杆或船舷位置建立清楚；不要让人物在没有空间依据的情况下突然飞起、跌落或横移。
- 古装打斗里的衣摆、披风、长发、袖摆和挂饰只能服务主动作，不要让它们抢走动作逻辑。若当前镜头已经有挥砍、格挡、刺入、银针出手或中招反应，就优先保住动作链和命中关系，不要再叠加过多飘动物。`),
		},
		{
			Name:        "多人对白",
			Slug:        "multi-dialogue",
			Description: "适用于三人以上同场交流、审讯、争执、会议、群像谈判等场景。",
			SortOrder:   50,
			Rules: strings.TrimSpace(`- 三人及以上的对白场景，先建立清楚位置关系，再决定当前镜头只看谁。每个镜头必须明确 1 个主说话者、1 个主要听者，其余人只承担空间交代、视线承接和弱反应。
- 不要把三人以上的完整往返对白硬塞进同一镜头；只要台词顺序、说话归属或听者反应开始不清楚，就拆成更多相邻镜头。
- 多人对话必须稳定保留左右关系、前后层次、视线方向和谁在等回应；不要让人物无缘由换边、换位、抢口型或突然接管主位。
- 如果当前场景是审讯、质问、谈判、对峙、会议、宴席交锋、群像争执或课堂点名，必须先建立谁在高位、谁在被问、谁在旁听、谁在观察；不要把所有人写成同等强度的平权说话者。
- 多人对白镜头里，背景人物默认只承担压低议论、短暂停顿、同步转头、交换目光、肩线收紧、呼吸变化或轻微后撤半步这类弱反应；除非脚本明确要求插话、拍桌、起身、离席或逼近，不要让背景人物突然抢口型或抢主位。
- 多人对白如果需要连续正反打、过肩、侧拍或群像反应，必须让视线目标、左右关系和谁在等待回应保持一致；不要让上一镜在左的人下一镜无缘由跑到右侧，也不要让听者和说话者的位置关系漂移。 `),
		},
		{
			Name:        "固定IP/吉祥物",
			Slug:        "fixed-ip-mascot",
			Description: "适用于固定主角、文旅IP、品牌吉祥物、儿童向卡通角色等需要跨镜头稳定复现的题材。",
			SortOrder:   60,
			Rules: strings.TrimSpace(`- 若当前故事存在固定主角、文旅IP、品牌吉祥物或反复出现的卡通角色，先为该角色建立稳定外观 canon，并在后续镜头持续继承：头身比、脸型、发型、刘海或鬓角、眼睛形状、鼻口结构、主副配色、服装轮廓、裤装或裙摆、鞋靴样式都要保持一致；除非剧情明确写出变化，不要自行换脸、换发型、换年龄感、换性别感、换服装主色或换鞋。
- 固定IP角色每次出场时，都要重复足够完整、当前可见的识别锚点，不要因为前文已经出现过就把人物压缩成几笔弱描述。单人镜头要把脸部、发型、服装主色、下装和鞋靴写清；双人、群像和动作镜头里，也必须保住主角当前可见的稳定锚点，不能因为同时出现其他角色或道具就把主角写弱。
- 若当前镜头里主角需要承担后续动作、反应、说话、互动或视频主位，首帧图必须先让主角以可识别方式出现。主角不能只剩一点侧脸、模糊边缘、局部轮廓或被前景主体压到边缘；至少要建立足够稳定的脸部、发型和服装识别信息，让后续视频继续沿用同一个角色。
- 若当前镜头里只能看到主角的手、前臂、肩背、局部侧脸或身体局部，也必须把当前仍可见的服装颜色、袖口、外层轮廓、手持物和体型比例补足写清，避免模型把同一个角色补成另一个人。局部镜头不能只写“一只手”“一个背影”“一点侧脸”后让模型自己猜。
- 固定IP角色的脸部关键识别区不要被杯子、书本、手机、纸张、武器、食物、道具或前景杂物挡住；如果后续视频还要让这个角色继续表演、说话、转向或互动，首帧里就必须让眉眼、鼻梁、嘴周、下颌和稳定发型尽量清楚可见。
- 固定IP角色若是Q版、吉祥物、儿童向主角或大头身角色，必须持续保持同一套头身比、脸部比例和眼睛结构，不要在远景、双人镜头、动作镜头或边缘构图里把同一角色忽然画成更年幼、更写实、比例不同或像另一个人物。
- 若当前镜头中主角需要和另一位重要角色联动，而主角又处在画面边缘、背身、局部遮挡或远距离状态，就应优先补强主角当前可见锚点，让模型仍能认出这是同一个角色；不要把主角压得过弱，再让视频阶段自由补脸。 `),
		},
	}

	tx := db.DB.Begin()
	for _, tag := range defaultTags {
		var existing models.AutoGenerateTag
		err := tx.Where("slug = ?", tag.Slug).First(&existing).Error
		switch {
		case err == nil:
			// Preserve user-edited tag content; only seed missing defaults.
			_ = existing
		case err != nil && err != gorm.ErrRecordNotFound:
			tx.Rollback()
			Log(LogLevelError, "初始化自动剧情标签失败", fmt.Sprintf("查询标签 %s 失败: %v", tag.Name, err))
			return
		default:
			tag.CreatedAt = time.Now()
			tag.UpdatedAt = time.Now()
			if err := tx.Create(&tag).Error; err != nil {
				tx.Rollback()
				Log(LogLevelError, "初始化自动剧情标签失败", fmt.Sprintf("插入标签 %s 失败: %v", tag.Name, err))
				return
			}
		}
	}
	tx.Commit()
	Log(LogLevelInfo, "初始化自动剧情标签", fmt.Sprintf("系统启动时检查了 %d 个默认自动剧情标签，缺失项已自动补齐", len(defaultTags)))
}
