import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { FileJson, FolderOpen, RefreshCw, Settings, Sparkles, Tags } from "lucide-react";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";

import type { AutoGenerateDraft, AutoGenerateTag, LLMStreamState, Project } from "@/types";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";

interface BackgroundTask {
  id: string;
  type: string;
  status: "pending" | "running" | "completed" | "failed";
  progress: number;
  result: string;
  error: string;
  created_at: string;
  updated_at: string;
}

const extractDownloadFilename = (contentDisposition: string | undefined, fallback: string) => {
  if (!contentDisposition) return fallback;
  const utfMatch = contentDisposition.match(/filename\*=UTF-8''([^;]+)/i);
  if (utfMatch?.[1]) {
    try {
      return decodeURIComponent(utfMatch[1]);
    } catch {
      return utfMatch[1];
    }
  }
  const plainMatch = contentDisposition.match(/filename=\"?([^\";]+)\"?/i);
  return plainMatch?.[1] || fallback;
};

const triggerBlobDownload = (blob: Blob, filename: string) => {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => window.URL.revokeObjectURL(url), 1000);
};

export default function AutoSeries() {
  const navigate = useNavigate();
  const [projects, setProjects] = useState<Project[]>([]);
  const [autoGenerateTags, setAutoGenerateTags] = useState<AutoGenerateTag[]>([]);
  const [loading, setLoading] = useState(false);
  const [currentProject, setCurrentProject] = useState<Project | null>(null);
  const [isImportingStory, setIsImportingStory] = useState(false);

  const [genPlot, setGenPlot] = useState("");
  const [genEpisode, setGenEpisode] = useState(1);
  const [genGenerationMode, setGenGenerationMode] = useState<"narration" | "high_quality" | "storyboard">("high_quality");
  const [genTagIds, setGenTagIds] = useState<number[]>([]);
  const [genLoading, setGenLoading] = useState(false);
  const [autoGenerateDraft, setAutoGenerateDraft] = useState<AutoGenerateDraft | null>(null);
  const [genTaskId, setGenTaskId] = useState("");
  const [genTask, setGenTask] = useState<BackgroundTask | null>(null);
  const [genTaskStream, setGenTaskStream] = useState<LLMStreamState | null>(null);
  const [showTaskStream, setShowTaskStream] = useState(true);
  const taskStreamRef = useRef<HTMLDivElement | null>(null);

  const [importEpisode, setImportEpisode] = useState(1);
  const [importStoryJSON, setImportStoryJSON] = useState("");
  const [importLoading, setImportLoading] = useState(false);
  const [exportLoading, setExportLoading] = useState(false);

  useEffect(() => {
    fetchProjects();
    fetchAutoGenerateTags();
  }, []);

  useEffect(() => {
    if (!currentProject && projects.length > 0) {
      void selectProject(projects[0]);
    }
  }, [projects, currentProject]);

  const resolveDraftGenerationMode = (draft?: Partial<AutoGenerateDraft> | null) => {
    const rawMode = String(draft?.generation_mode || "").trim();
    if (rawMode === "narration" || rawMode === "high_quality" || rawMode === "storyboard") {
      return rawMode;
    }
    return draft?.allow_character_speech ? "high_quality" : "narration";
  };

  const modeAllowsCharacterSpeech = (mode: "narration" | "high_quality" | "storyboard") => mode !== "narration";

  const getDefaultAutoGenerateEpisode = (project?: Partial<Project>) => {
    const nextEpisode = Number(project?.next_auto_generate_episode || 1);
    return nextEpisode > 0 ? nextEpisode : 1;
  };

  const fetchProjects = async () => {
    setLoading(true);
    try {
      const res = await axios.get("/api/projects");
      setProjects(res.data || []);
    } catch (err) {
      console.error(err);
      toast.error("获取剧情项目失败");
    } finally {
      setLoading(false);
    }
  };

  const fetchAutoGenerateTags = async () => {
    try {
      const res = await axios.get("/api/auto-generate-tags");
      setAutoGenerateTags(Array.isArray(res.data) ? res.data : []);
    } catch (err) {
      console.error(err);
      toast.error("读取标签失败");
    }
  };

  const loadAutoGenerateDraft = async (project: Project) => {
    try {
      const res = await axios.get(`/api/projects/${project.id}/auto-generate-draft`);
      const draft = res.data as AutoGenerateDraft;
      setAutoGenerateDraft(draft);
      setGenTaskId(String(draft.current_task_id || "").trim());
      setGenTask(null);
      setGenTaskStream(null);
      setGenPlot(draft.plot || "");
      setGenGenerationMode(resolveDraftGenerationMode(draft));
      setGenTagIds(Array.isArray(draft.tag_ids) ? draft.tag_ids.map(Number).filter((id) => Number.isFinite(id) && id > 0) : []);
      const suggestedEpisode = draft.stage === "completed"
        ? (project.is_empty ? 1 : getDefaultAutoGenerateEpisode(project))
        : (draft.episode || (project.is_empty ? 1 : getDefaultAutoGenerateEpisode(project)));
      setGenEpisode(suggestedEpisode);
    } catch (err: any) {
      if (err?.response?.status === 404) {
        setAutoGenerateDraft(null);
        setGenTaskId("");
        setGenTask(null);
        setGenTaskStream(null);
        setGenGenerationMode("high_quality");
        setGenTagIds([]);
        setGenPlot("");
        setGenEpisode(project.is_empty ? 1 : getDefaultAutoGenerateEpisode(project));
        return;
      }
      console.error(err);
      toast.error("读取一键剧集草稿失败");
    }
  };

  const selectProject = async (project: Project) => {
    setCurrentProject(project);
    setIsImportingStory(false);
    setImportStoryJSON("");
    setGenTaskId("");
    setGenTask(null);
    setGenTaskStream(null);
    setShowTaskStream(true);
    await loadAutoGenerateDraft(project);
  };

  const toggleAutoGenerateTag = (tagId: number) => {
    setGenTagIds((prev) => (prev.includes(tagId) ? prev.filter((id) => id !== tagId) : [...prev, tagId].sort((a, b) => a - b)));
  };

  const canContinueAutoGenerate = !!autoGenerateDraft && autoGenerateDraft.stage === "failed" && !!String(autoGenerateDraft.current_task_id || "").trim();
  const isCurrentTaskActive = !!genTaskId && (
    genTask?.status === "pending" ||
    genTask?.status === "running" ||
    (!genTask && (autoGenerateDraft?.stage === "queued" || autoGenerateDraft?.stage === "generating"))
  );
  const completedScenes = autoGenerateDraft?.completed_scenes || 0;
  const currentProjectIsEmpty = !!currentProject?.is_empty;

  const continueAutoGenerate = async () => {
    if (!currentProject?.id) return;
    setGenLoading(true);
    try {
      const res = await axios.post(`/api/projects/${currentProject.id}/auto-generate-draft/continue`);
      const nextTaskId = String(res.data?.task_id || "").trim();
      setGenTaskId(nextTaskId);
      setGenTask(null);
      setGenTaskStream(null);
      toast.success("一键剧集续写任务已提交");
      await fetchProjects();
      if (autoGenerateDraft) {
        setAutoGenerateDraft({
          ...autoGenerateDraft,
          current_task_id: nextTaskId,
          stage: "queued",
          last_error: "",
        });
      }
    } catch (err: any) {
      console.error(err);
      toast.error(err.response?.data?.error || "继续生成失败");
    } finally {
      setGenLoading(false);
    }
  };

  const submitAutoGenerate = async () => {
    if (!currentProject?.id) return;
    if (isCurrentTaskActive) {
      toast.error("当前一键剧集任务仍在运行，请等待完成后再提交");
      return;
    }
    setGenLoading(true);
    try {
      const payload = {
        plot: genPlot,
        episode: Number(genEpisode),
        generation_mode: genGenerationMode,
        tag_ids: genTagIds,
        allow_character_speech: modeAllowsCharacterSpeech(genGenerationMode),
      };
      const res = await axios.post(`/api/projects/${currentProject.id}/auto-generate`, payload);
      const nextTaskId = String(res.data?.task_id || "").trim();
      setGenTaskId(nextTaskId);
      setGenTask(null);
      setGenTaskStream(null);
      toast.success("一键剧集任务已提交");
      await fetchProjects();
      if (autoGenerateDraft) {
        setAutoGenerateDraft({
          ...autoGenerateDraft,
          current_task_id: nextTaskId,
          generation_mode: genGenerationMode,
          tag_ids: genTagIds,
          allow_character_speech: modeAllowsCharacterSpeech(genGenerationMode),
          stage: "queued",
          last_error: "",
        });
      }
    } catch (err: any) {
      console.error(err);
      toast.error(err.response?.data?.error || "生成失败");
    } finally {
      setGenLoading(false);
    }
  };

  const handleAutoGenerate = () => {
    if (!currentProject?.id) return;
    if (!genPlot.trim()) {
      toast.error("请输入小说或剧本内容");
      return;
    }
    if (canContinueAutoGenerate) {
      void continueAutoGenerate();
      return;
    }
    void submitAutoGenerate();
  };

  const handleImportStoryJSON = async () => {
    if (!currentProject?.id) return;
    if (!importStoryJSON.trim()) {
      toast.error("请输入要导入的 JSON 内容");
      return;
    }
    setImportLoading(true);
    try {
      const res = await axios.post(`/api/projects/${currentProject.id}/import-story-json`, {
        episode: Number(importEpisode),
        story_json: importStoryJSON,
      });
      toast.success(`导入成功，第 ${res.data?.episode || importEpisode} 集已写入，共 ${res.data?.total_scenes || 0} 镜`);
      setImportStoryJSON("");
      setIsImportingStory(false);
      await fetchProjects();
      await loadAutoGenerateDraft(currentProject);
    } catch (err: any) {
      console.error(err);
      toast.error(err.response?.data?.error || "导入失败");
    } finally {
      setImportLoading(false);
    }
  };

  const handleExportStoryJSON = async () => {
    if (!currentProject?.id) return;
    setExportLoading(true);
    try {
      const res = await axios.post(`/api/projects/${currentProject.id}/export-story-json`, {
        episode: Number(importEpisode),
      }, {
        responseType: "blob",
      });
      const filename = extractDownloadFilename(
        res.headers["content-disposition"],
        `project_${currentProject.id}_episode_${importEpisode}_story.json`,
      );
      triggerBlobDownload(res.data, filename);
      toast.success(`第 ${importEpisode} 集 JSON 已导出`);
    } catch (err: any) {
      console.error(err);
      const blob = err?.response?.data;
      if (blob instanceof Blob) {
        blob.text().then((text) => {
          try {
            const parsed = JSON.parse(text);
            toast.error(parsed?.error || "导出失败");
          } catch {
            toast.error("导出失败");
          }
        });
      } else {
        toast.error(err.response?.data?.error || "导出失败");
      }
    } finally {
      setExportLoading(false);
    }
  };

  useEffect(() => {
    if (!currentProject?.id) return;
    const projectId = Number(currentProject.id);
    const draftTimer = window.setInterval(() => {
      axios.get(`/api/projects/${projectId}/auto-generate-draft`)
        .then((res) => setAutoGenerateDraft(res.data as AutoGenerateDraft))
        .catch((err) => {
          if (err?.response?.status !== 404) {
            console.error(err);
          }
        });
    }, 2000);
    return () => window.clearInterval(draftTimer);
  }, [currentProject?.id]);

  useEffect(() => {
    if (!genTaskId || !currentProject?.id) return;
    let stopped = false;

    const fetchTaskState = () => {
      axios.get(`/api/tasks/${genTaskId}`)
        .then((res) => {
          if (stopped) return;
          const task = res.data as BackgroundTask;
          setGenTask(task);
          if (task.status === "completed" || task.status === "failed") {
            void fetchProjects();
          }
        })
        .catch((err) => {
          if (!stopped) console.error(err);
        });
    };

    const fetchTaskStream = () => {
      axios.get(`/api/tasks/${genTaskId}/llm-stream`)
        .then((res) => {
          if (!stopped) {
            setGenTaskStream(res.data?.stream || null);
          }
        })
        .catch((err) => {
          if (!stopped) console.error(err);
        });
    };

    fetchTaskState();
    fetchTaskStream();

    const taskTimer = window.setInterval(fetchTaskState, 2000);
    const streamTimer = window.setInterval(() => {
      if (showTaskStream || genTask?.status === "running" || genTask?.status === "pending") {
        fetchTaskStream();
      }
    }, 1000);

    return () => {
      stopped = true;
      window.clearInterval(taskTimer);
      window.clearInterval(streamTimer);
    };
  }, [genTaskId, currentProject?.id, showTaskStream, genTask?.status]);

  useEffect(() => {
    if (!showTaskStream) return;
    const streamEl = taskStreamRef.current;
    if (!streamEl) return;
    const rafId = window.requestAnimationFrame(() => {
      streamEl.scrollTop = streamEl.scrollHeight;
    });
    return () => window.cancelAnimationFrame(rafId);
  }, [showTaskStream, genTaskStream?.content]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">一键剧集</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            独立管理自动剧集生成与标准剧情 JSON 导入导出，不再和剧情管理列表混在一起。
          </p>
        </div>
        <button
          onClick={fetchProjects}
          disabled={loading}
          className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
          刷新
        </button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[320px_minmax(0,1fr)] gap-6">
        <div className="space-y-3">
          <div className="rounded-xl border border-border bg-card p-4 shadow-sm">
            <div className="text-sm font-medium">选择项目</div>
            <p className="mt-1 text-xs text-muted-foreground">
              先选择一个剧情项目，再开始一键剧集或导入/导出 JSON。
            </p>
          </div>

          <div className="space-y-3">
            {projects.map((project) => {
              const active = currentProject?.id === project.id;
              return (
                <button
                  key={project.id}
                  type="button"
                  onClick={() => void selectProject(project)}
                  className={`w-full rounded-xl border p-4 text-left transition-colors ${
                    active ? "border-primary bg-primary/5" : "border-border bg-card hover:bg-accent/40"
                  }`}
                >
                  <div className="font-medium">{project.name}</div>
                  <div className="mt-1 text-xs font-mono text-muted-foreground">{project.code}</div>
                  <div className="mt-2 text-xs text-muted-foreground line-clamp-2">{project.description || "暂无备注"}</div>
                </button>
              );
            })}
          </div>
        </div>

        <div className="min-w-0 space-y-6">
          {!currentProject ? (
            <div className="rounded-xl border border-dashed border-border bg-card/50 p-10 text-center text-muted-foreground">
              请先从左侧选择一个项目。
            </div>
          ) : (
            <>
              <div className="rounded-xl border border-border bg-card p-4 shadow-sm">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <h2 className="text-xl font-semibold">{currentProject.name}</h2>
                    <p className="mt-1 text-sm text-muted-foreground">{currentProject.description || "暂无备注"}</p>
                    <p className="mt-2 text-xs font-mono text-muted-foreground">项目编号：{currentProject.code}</p>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => navigate(`/projects/${currentProject.id}`)}
                      className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors"
                    >
                      <FolderOpen className="w-4 h-4" />
                      进入剧情管理
                    </button>
                    <button
                      onClick={() => setIsImportingStory((prev) => !prev)}
                      className="flex items-center gap-2 bg-sky-500/10 text-sky-600 hover:bg-sky-500/20 px-4 py-2 rounded-md transition-colors border border-sky-500/20"
                    >
                      <FileJson className="w-4 h-4" />
                      {isImportingStory ? "收起 JSON 工具" : "导入 / 导出 JSON"}
                    </button>
                  </div>
                </div>
              </div>

              <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm space-y-3">
                <div>
                  <div className="font-medium text-foreground">一键剧集模式</div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    先明确告诉后端走哪条提示词分支，再按你勾选的题材标签追加专属规则，避免把所有规则都塞给 LLM。
                  </p>
                </div>
                <RadioGroup
                  value={genGenerationMode}
                  onValueChange={(value) => setGenGenerationMode(value as "narration" | "high_quality" | "storyboard")}
                  className="gap-3"
                  disabled={genLoading || isCurrentTaskActive}
                >
                  <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                    <RadioGroupItem value="narration" className="mt-0.5" />
                    <div>
                      <div className="font-medium text-foreground">旁白模式</div>
                      <p className="mt-1 text-xs text-muted-foreground">保持当前旁白驱动逻辑，适合解说式叙事和普通一键剧集生成。</p>
                    </div>
                  </label>
                  <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                    <RadioGroupItem value="high_quality" className="mt-0.5" />
                    <div>
                      <div className="font-medium text-foreground">高质量模式</div>
                      <p className="mt-1 text-xs text-muted-foreground">面向小说或故事原文，按导演视角重构镜头，不依赖旁白推进剧情。</p>
                    </div>
                  </label>
                  <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                    <RadioGroupItem value="storyboard" className="mt-0.5" />
                    <div>
                      <div className="font-medium text-foreground">严格分镜脚本模式</div>
                      <p className="mt-1 text-xs text-muted-foreground">面向已写好的分镜脚本或拍摄脚本，优先保留原镜头顺序、对白归属和镜头意图。</p>
                    </div>
                  </label>
                </RadioGroup>
              </div>

              <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm space-y-3">
                <div className="flex items-start gap-2">
                  <Tags className="w-4 h-4 mt-0.5 text-primary" />
                  <div>
                    <div className="font-medium text-foreground">标签增强</div>
                    <p className="mt-1 text-xs text-muted-foreground">
                      可同时勾选多个标签。勾选后，对应规则会追加到本次一键剧集的 LLM 输入里。
                    </p>
                  </div>
                </div>
                {autoGenerateTags.length === 0 ? (
                  <div className="rounded-md border border-dashed border-border bg-background/70 px-3 py-3 text-xs text-muted-foreground">
                    还没有可选标签。你可以先去左侧「标签管理」页面维护规则。
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {autoGenerateTags.map((tag) => {
                      const selected = genTagIds.includes(tag.id);
                      return (
                        <button
                          key={tag.id}
                          type="button"
                          onClick={() => toggleAutoGenerateTag(tag.id)}
                          disabled={genLoading || isCurrentTaskActive}
                          className={`text-left rounded-md border px-3 py-3 transition-colors ${
                            selected ? "border-primary bg-primary/10" : "border-border bg-background/70 hover:bg-accent/60"
                          } disabled:opacity-60`}
                        >
                          <div className="font-medium text-foreground">{tag.name}</div>
                          <p className="mt-1 text-xs text-muted-foreground line-clamp-3">{tag.description}</p>
                        </button>
                      );
                    })}
                  </div>
                )}
              </div>

              <div className="space-y-4 rounded-xl border border-border bg-card p-4 shadow-sm">
                <div>
                  <label className="block text-sm font-medium mb-2">
                    小说 / 剧本内容 <span className="text-red-500">*</span>
                  </label>
                  <Textarea
                    value={genPlot}
                    onChange={(e) => setGenPlot(e.target.value)}
                    placeholder="请输入本集小说内容或剧本全文，系统会一次性生成 characters 与 scenes..."
                    className="min-h-[180px]"
                    disabled={genLoading}
                  />
                </div>

                {!currentProjectIsEmpty && (
                  <div>
                    <label className="block text-sm font-medium mb-2">生成集数</label>
                    <Input
                      type="number"
                      min={1}
                      value={genEpisode}
                      onChange={(e) => setGenEpisode(Number(e.target.value))}
                      disabled={genLoading}
                    />
                    <p className="mt-2 text-xs text-muted-foreground">当前项目已经有内容，默认会续到下一集。你也可以按需要改成别的目标集数。</p>
                  </div>
                )}

                {currentProjectIsEmpty && (
                  <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm text-muted-foreground">
                    当前项目还是空项目，本次会直接从第 1 集开始创建。
                  </div>
                )}

                <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm">
                  <div className="font-medium text-amber-600">当前系统固定使用无参考图模式</div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    一键剧集只负责生成角色与镜头文本结果，后续场景图统一直接使用 image_prompt 提交到图像工作流。
                  </p>
                </div>

                <div className="flex flex-wrap justify-end gap-3 pt-2">
                  <button
                    onClick={() => setShowTaskStream((prev) => !prev)}
                    disabled={!genTaskId}
                    className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                  >
                    <Settings className="w-4 h-4" />
                    {showTaskStream ? "隐藏当前任务 LLM 流" : "查看当前任务 LLM 流"}
                  </button>
                  <button
                    onClick={() => navigate("/logs")}
                    disabled={genLoading}
                    className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                  >
                    <Settings className="w-4 h-4" />
                    全局日志
                  </button>
                  <button
                    onClick={handleAutoGenerate}
                    disabled={genLoading || isCurrentTaskActive}
                    className="flex items-center gap-2 bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors disabled:opacity-70"
                  >
                    {genLoading ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin" />
                        AI 生成中...
                      </>
                    ) : isCurrentTaskActive ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin" />
                        当前任务执行中
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        {canContinueAutoGenerate ? "继续生成" : "开始生成"}
                      </>
                    )}
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_420px] gap-6">
                <div className="space-y-4">
                  {autoGenerateDraft?.characters_json && (
                    <div>
                      <label className="block text-sm font-medium mb-2">角色结果 (JSON)</label>
                      <Textarea value={autoGenerateDraft.characters_json} className="min-h-[180px] font-mono text-xs" readOnly />
                    </div>
                  )}
                  {autoGenerateDraft?.scenes_json && (
                    <div>
                      <label className="block text-sm font-medium mb-2">镜头结果 (JSON{completedScenes > 0 ? `，共 ${completedScenes} 镜` : ""})</label>
                      <Textarea value={autoGenerateDraft.scenes_json} className="min-h-[240px] font-mono text-xs" readOnly />
                    </div>
                  )}
                  {autoGenerateDraft?.episode_memory_json && (
                    <div>
                      <label className="block text-sm font-medium mb-2">跨集记忆结果 (JSON)</label>
                      <Textarea value={autoGenerateDraft.episode_memory_json} className="min-h-[180px] font-mono text-xs" readOnly />
                    </div>
                  )}
                </div>

                <div className="space-y-4">
                  <div className="rounded-xl border border-border bg-card p-4 shadow-sm space-y-2">
                    <div className="text-sm font-medium">任务状态</div>
                    <div className="text-sm text-muted-foreground">
                      {genTaskId ? `任务 ID：${genTaskId}` : "当前还没有运行中的一键剧集任务"}
                    </div>
                    {genTask ? (
                      <div className="text-sm text-muted-foreground">
                        状态：{genTask.status} / {typeof genTask.progress === "number" ? `${genTask.progress}%` : "0%"}
                      </div>
                    ) : null}
                    {autoGenerateDraft?.last_error ? (
                      <div className="rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2 text-xs text-destructive break-words">
                        上次失败原因：{autoGenerateDraft.last_error}
                      </div>
                    ) : null}
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2">
                      当前任务实时 LLM 流
                      {genTaskStream?.status ? `（${genTaskStream.status}）` : ""}
                    </label>
                    <div
                      ref={taskStreamRef}
                      className="h-[420px] min-h-[420px] overflow-y-auto rounded-md border border-input bg-background px-3 py-2 font-mono text-xs whitespace-pre-wrap break-words"
                    >
                      {genTaskId ? (genTaskStream?.content || "正在等待当前任务返回实时流...") : "当前还没有任务流"}
                    </div>
                  </div>
                </div>
              </div>

              {isImportingStory ? (
                <div className="rounded-xl border border-border bg-card p-4 shadow-sm space-y-5">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h2 className="text-lg font-semibold">导入 / 导出标准剧情 JSON</h2>
                      <p className="mt-1 text-sm text-muted-foreground">
                        这里用于导入外部 AI 已经生成好的严格 JSON，或者把当前项目某一集导出成同结构 JSON。
                      </p>
                    </div>
                    <button
                      onClick={() => setIsImportingStory(false)}
                      className="rounded-md border border-border px-3 py-2 text-sm hover:bg-accent transition-colors"
                    >
                      收起
                    </button>
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2">导入集数</label>
                    <Input
                      type="number"
                      min={1}
                      value={importEpisode}
                      onChange={(e) => setImportEpisode(Number(e.target.value))}
                      disabled={importLoading}
                    />
                  </div>

                  <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-xs text-muted-foreground space-y-1">
                    <p>固定要求：</p>
                    <p>1. 顶层必须包含 `total_scenes`、`characters`、`scenes`、`episode_memory`。</p>
                    <p>2. `image_prompt` 必须是 5 行：主体 / 场景 / 构图 / 光影 / 约束。</p>
                    <p>3. `video_prompt` 必须是 5 行：`Style:` / `Phase 1 (...)` / `Audio:` / `Phase 2 (...)` / `Audio:`。</p>
                    <p>4. 如果项目已有锁定角色，`characters` 里只能放新角色，旧角色不要重复返回。</p>
                    <p>5. 当前主链路不再要求返回 `dialogue`，重点放在 `narration`、`image_prompt`、`video_prompt` 与 `duration_seconds`。</p>
                    <p>6. 所有字段值必须使用简体中文；只有 `video_prompt` 的 5 个固定标签保留英文。</p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium mb-2">导入 JSON</label>
                    <Textarea
                      value={importStoryJSON}
                      onChange={(e) => setImportStoryJSON(e.target.value)}
                      placeholder={`{\n  "total_scenes": 2,\n  "characters": [],\n  "scenes": [],\n  "episode_memory": {}\n}`}
                      className="min-h-[360px] font-mono text-xs"
                      disabled={importLoading}
                    />
                  </div>

                  <div className="flex justify-end gap-3">
                    <button
                      onClick={handleExportStoryJSON}
                      disabled={importLoading || exportLoading}
                      className="flex items-center gap-2 bg-secondary text-secondary-foreground px-6 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                    >
                      {exportLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <FileJson className="w-4 h-4" />}
                      导出当前集 JSON
                    </button>
                    <button
                      onClick={handleImportStoryJSON}
                      disabled={importLoading || exportLoading}
                      className="flex items-center gap-2 bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors disabled:opacity-70"
                    >
                      {importLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <FileJson className="w-4 h-4" />}
                      导入并入库
                    </button>
                  </div>
                </div>
              ) : null}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
