import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Plus, Trash2, Edit2, RotateCcw, X, Save, Folder, Settings, Sparkles, FileJson, Tags } from "lucide-react";
import type { Project, ArtStyle, AutoGenerateDraft, LLMStreamState, AutoGenerateTag } from "@/types";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";

import { Combobox } from "@/components/ui/combobox";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";

interface BackgroundTask {
    id: string;
    type: string;
    status: "pending" | "running" | "completed" | "failed";
    progress: number;
    result: string;
    error: string;
    created_at: string;
    updated_at: string;
}

const extractDownloadFilename = (
    contentDisposition: string | undefined,
    fallback: string,
) => {
    if (!contentDisposition) return fallback;
    const utfMatch = contentDisposition.match(/filename\*=UTF-8''([^;]+)/i);
    if (utfMatch?.[1]) {
        try {
            return decodeURIComponent(utfMatch[1]);
        } catch {
            return utfMatch[1];
        }
    }
    const plainMatch = contentDisposition.match(/filename=\"?([^\";]+)\"?/i);
    return plainMatch?.[1] || fallback;
};

const triggerBlobDownload = (blob: Blob, filename: string) => {
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.setTimeout(() => window.URL.revokeObjectURL(url), 1000);
};

export default function Projects() {
    const navigate = useNavigate();
    const [projects, setProjects] = useState<Project[]>([]);
    const [styles, setStyles] = useState<ArtStyle[]>([]);
    const [autoGenerateTags, setAutoGenerateTags] = useState<AutoGenerateTag[]>([]);
    const [loading, setLoading] = useState(false);
    const [isEditing, setIsEditing] = useState(false);
    const [isAutoGenerating, setIsAutoGenerating] = useState(false);
    const [isImportingStory, setIsImportingStory] = useState(false);
    const [currentProject, setCurrentProject] = useState<Partial<Project>>({});
    
    // Auto Generate State
    const [genPlot, setGenPlot] = useState("");
    const [genEpisode, setGenEpisode] = useState(1);
    const [genGenerationMode, setGenGenerationMode] = useState<"narration" | "high_quality" | "storyboard">("high_quality");
    const [genTagIds, setGenTagIds] = useState<number[]>([]);
    const [genLoading, setGenLoading] = useState(false);
    const [autoGenerateDraft, setAutoGenerateDraft] = useState<AutoGenerateDraft | null>(null);
    const [genTaskId, setGenTaskId] = useState("");
    const [genTask, setGenTask] = useState<BackgroundTask | null>(null);
    const [genTaskStream, setGenTaskStream] = useState<LLMStreamState | null>(null);
    const [showTaskStream, setShowTaskStream] = useState(false);
    const taskStreamRef = useRef<HTMLDivElement | null>(null);
    const [importEpisode, setImportEpisode] = useState(1);
    const [importStoryJSON, setImportStoryJSON] = useState("");
    const [importLoading, setImportLoading] = useState(false);
    const [exportLoading, setExportLoading] = useState(false);

    useEffect(() => {
        fetchProjects();
        fetchStyles();
        fetchAutoGenerateTags();
    }, []);

    const modeAllowsCharacterSpeech = (mode: "narration" | "high_quality" | "storyboard") => {
        return mode !== "narration";
    };

    const toggleAutoGenerateTag = (tagId: number) => {
        setGenTagIds(prev => {
            if (prev.includes(tagId)) {
                return prev.filter(id => id !== tagId);
            }
            return [...prev, tagId].sort((a, b) => a - b);
        });
    };

    const fetchProjects = () => {
        setLoading(true);
        axios.get("/api/projects")
            .then(res => setProjects(res.data))
            .catch(err => {
                console.error(err);
                toast.error("获取剧情项目失败");
            })
            .finally(() => setLoading(false));
    };

    const fetchStyles = () => {
        axios.get("/api/styles")
            .then(res => {
                const data = res.data;
                if (Array.isArray(data) && data.length === 0) {
                     axios.post("/api/styles/init")
                        .then(() => fetchStyles()) 
                        .catch(err => console.error("Init failed", err));
                } else {
                    setStyles(data);
                }
            })
            .catch(err => console.error(err));
    };

    const fetchAutoGenerateTags = () => {
        axios.get("/api/auto-generate-tags")
            .then(res => {
                setAutoGenerateTags(Array.isArray(res.data) ? res.data : []);
            })
            .catch(err => {
                console.error(err);
                toast.error("读取标签失败");
            });
    };

    const openAutoGenerateModal = (project: Project) => {
        setCurrentProject(project);
        setGenPlot("");
        setGenTask(null);
        setGenTaskStream(null);
        setShowTaskStream(false);
        setGenTaskId("");
        setGenTagIds([]);
        setGenGenerationMode("high_quality");
        setGenEpisode(1);
        setAutoGenerateDraft(null);
        setIsAutoGenerating(true);

        axios.get(`/api/projects/${project.id}/auto-generate-draft`)
            .then((res) => {
                const draft = res.data as AutoGenerateDraft;
                setAutoGenerateDraft(draft);
                setGenPlot(draft.plot || "");
                setGenEpisode(draft.episode || 1);
                setGenGenerationMode((draft.generation_mode as "narration" | "high_quality" | "storyboard") || "high_quality");
                setGenTagIds(Array.isArray(draft.tag_ids) ? draft.tag_ids : []);
                const taskId = String(draft.current_task_id || "").trim();
                setGenTaskId(taskId);
            })
            .catch((err) => {
                if (err?.response?.status !== 404) {
                    console.error(err);
                    toast.error("读取一键剧集草稿失败");
                }
            });
    };

    const openImportStoryModal = (project: Project) => {
        setCurrentProject(project);
        setImportEpisode(1);
        setImportStoryJSON("");
        setIsImportingStory(true);
    };

    const handleSave = () => {
        if (!currentProject.name || !currentProject.code || !currentProject.art_style_id) {
            toast.error("请填写所有必填字段 (名称, 编号, 画风)");
            return;
        }

        if (!currentProject.id && !/^[a-zA-Z0-9_-]+$/.test(currentProject.code)) {
            toast.error("项目编号只允许输入英文、数字、下划线或连字符");
            return;
        }

        const payload = {
            ...currentProject,
            art_style_id: Number(currentProject.art_style_id),
            disable_reference_images: true,
        };

        const req = currentProject.id
            ? axios.put(`/api/projects/${currentProject.id}`, payload)
            : axios.post("/api/projects", payload);

        req.then(() => {
            setIsEditing(false);
            setCurrentProject({});
            fetchProjects();
            toast.success(currentProject.id ? "项目已更新" : "项目已创建");
        }).catch(err => {
            console.error(err);
            const msg = err.response?.data?.error || "保存失败";
            toast.error(msg);
        });
    };

    const handleDelete = (id: number) => {
        toast("该操作会删除项目的数据内容及所对应的文件夹内的全部资源！是否确认？", {
            action: {
                label: "确认删除",
                onClick: () => {
                    axios.delete(`/api/projects/${id}`)
                        .then(() => {
                            fetchProjects();
                            toast.success("项目已删除");
                        })
                        .catch(err => {
                            console.error(err);
                            toast.error("删除失败");
                        });
                }
            },
            cancel: {
                label: "取消",
                onClick: () => {},
            }
        });
    };

    const handleResetProjectContent = (project: Project) => {
        toast(`这会物理删除项目「${project.name}」下所有已生成的视频、图片和一键剧集数据，只保留项目名称、编号、画风和备注。是否确认清空内容？`, {
            action: {
                label: "确认清空",
                onClick: () => {
                    axios.post(`/api/projects/${project.id}/reset-content`)
                        .then(() => {
                            fetchProjects();
                            toast.success("项目内容已清空");
                        })
                        .catch(err => {
                            console.error(err);
                            const msg = err.response?.data?.error || "清空项目内容失败";
                            toast.error(msg);
                        });
                }
            },
            cancel: {
                label: "取消",
                onClick: () => {},
            }
        });
    };

    const handleAutoGenerate = () => {
        if (!currentProject.id) return;
        if (!genPlot.trim()) {
            toast.error("请输入小说或剧本内容");
            return;
        }
        if (canContinueAutoGenerate) {
            continueAutoGenerate();
            return;
        }
        submitAutoGenerate();
    };

    const continueAutoGenerate = () => {
        if (!currentProject.id) return;
        setGenLoading(true);
        axios.post(`/api/projects/${currentProject.id}/auto-generate-draft/continue`)
            .then(res => {
                const nextTaskId = String(res.data?.task_id || "").trim();
                setGenTaskId(nextTaskId);
                setGenTask(null);
                setGenTaskStream(null);
                setShowTaskStream(false);
                toast.success("一键剧集续写任务已提交");
                fetchProjects();
                if (autoGenerateDraft) {
                    setAutoGenerateDraft({
                        ...autoGenerateDraft,
                        current_task_id: nextTaskId,
                        stage: "queued",
                        last_error: "",
                    });
                }
            })
            .catch(err => {
                console.error(err);
                const msg = err.response?.data?.error || "继续生成失败";
                toast.error(msg);
            })
            .finally(() => setGenLoading(false));
    };

    const submitAutoGenerate = () => {
        const isCurrentTaskActive = !!genTaskId && (
            genTask?.status === "pending" ||
            genTask?.status === "running" ||
            (!genTask && (autoGenerateDraft?.stage === "queued" || autoGenerateDraft?.stage === "generating"))
        );
        if (isCurrentTaskActive) {
            toast.error("当前一键剧集任务仍在运行，请等待完成后再提交");
            return;
        }
        setGenLoading(true);
        const payload = {
            plot: genPlot,
            episode: Number(genEpisode),
            generation_mode: genGenerationMode,
            tag_ids: genTagIds,
            allow_character_speech: modeAllowsCharacterSpeech(genGenerationMode),
        };

        axios.post(`/api/projects/${currentProject.id}/auto-generate`, payload)
            .then(res => {
                const nextTaskId = String(res.data?.task_id || "").trim();
                setGenTaskId(nextTaskId);
                setGenTask(null);
                setGenTaskStream(null);
                setShowTaskStream(false);
                toast.success("自动生成任务已提交");
                fetchProjects();
                if (autoGenerateDraft) {
                    setAutoGenerateDraft({
                        ...autoGenerateDraft,
                        current_task_id: nextTaskId,
                        generation_mode: genGenerationMode,
                        tag_ids: genTagIds,
                        allow_character_speech: modeAllowsCharacterSpeech(genGenerationMode),
                        stage: "queued",
                        last_error: "",
                    });
                }
            })
            .catch(err => {
                console.error(err);
                const msg = err.response?.data?.error || "生成失败";
                toast.error(msg);
            })
            .finally(() => setGenLoading(false));
    };

    const handleImportStoryJSON = () => {
        if (!currentProject.id) return;
        if (!importStoryJSON.trim()) {
            toast.error("请输入要导入的 JSON 内容");
            return;
        }

        setImportLoading(true);
        axios.post(`/api/projects/${currentProject.id}/import-story-json`, {
            episode: Number(importEpisode),
            story_json: importStoryJSON,
        })
            .then((res) => {
                toast.success(`导入成功，第 ${res.data?.episode || importEpisode} 集已写入，共 ${res.data?.total_scenes || 0} 镜`);
                setIsImportingStory(false);
                setImportStoryJSON("");
                fetchProjects();
            })
            .catch((err) => {
                console.error(err);
                const msg = err.response?.data?.error || "导入失败";
                toast.error(msg);
            })
            .finally(() => setImportLoading(false));
    };

    const handleExportStoryJSON = () => {
        if (!currentProject.id) return;
        setExportLoading(true);
        axios.post(`/api/projects/${currentProject.id}/export-story-json`, {
            episode: Number(importEpisode),
        }, {
            responseType: "blob",
        })
            .then((res) => {
                const filename = extractDownloadFilename(
                    res.headers["content-disposition"],
                    `project_${currentProject.id}_episode_${importEpisode}_story.json`,
                );
                triggerBlobDownload(res.data, filename);
                toast.success(`第 ${importEpisode} 集 JSON 已导出`);
            })
            .catch((err) => {
                console.error(err);
                const blob = err?.response?.data;
                if (blob instanceof Blob) {
                    blob.text().then((text) => {
                        try {
                            const parsed = JSON.parse(text);
                            toast.error(parsed?.error || "导出失败");
                        } catch {
                            toast.error("导出失败");
                        }
                    });
                    return;
                }
                const msg = err.response?.data?.error || "导出失败";
                toast.error(msg);
            })
            .finally(() => setExportLoading(false));
    };

    useEffect(() => {
        if (!isAutoGenerating || !currentProject.id) return;

        const projectId = Number(currentProject.id);
        if (!projectId) return;

        const draftTimer = window.setInterval(() => {
            axios.get(`/api/projects/${projectId}/auto-generate-draft`)
                .then(res => setAutoGenerateDraft(res.data as AutoGenerateDraft))
                .catch((err) => {
                    if (err?.response?.status !== 404) {
                        console.error(err);
                    }
                });
        }, 2000);

        return () => window.clearInterval(draftTimer);
    }, [isAutoGenerating, currentProject.id]);

    useEffect(() => {
        if (!genTaskId || !isAutoGenerating) return;

        let stopped = false;

        const fetchTaskState = () => {
            axios.get(`/api/tasks/${genTaskId}`)
                .then(res => {
                    if (stopped) return;
                    const task = res.data as BackgroundTask;
                    setGenTask(task);
                    if (task.status === "completed" || task.status === "failed") {
                        fetchProjects();
                    }
                })
                .catch(err => {
                    if (!stopped) {
                        console.error(err);
                    }
                });
        };

        const fetchTaskStream = () => {
            axios.get(`/api/tasks/${genTaskId}/llm-stream`)
                .then(res => {
                    if (!stopped) {
                        setGenTaskStream(res.data?.stream || null);
                    }
                })
                .catch(err => {
                    if (!stopped) {
                        console.error(err);
                    }
                });
        };

        fetchTaskState();
        fetchTaskStream();

        const taskTimer = window.setInterval(fetchTaskState, 2000);
        const streamTimer = window.setInterval(() => {
            if (showTaskStream || genTask?.status === "running" || genTask?.status === "pending") {
                fetchTaskStream();
            }
        }, 1000);

        return () => {
            stopped = true;
            window.clearInterval(taskTimer);
            window.clearInterval(streamTimer);
        };
    }, [genTaskId, isAutoGenerating, showTaskStream, genTask?.status]);

    useEffect(() => {
        if (!showTaskStream) return;
        const streamEl = taskStreamRef.current;
        if (!streamEl) return;
        const rafId = window.requestAnimationFrame(() => {
            streamEl.scrollTop = streamEl.scrollHeight;
        });
        return () => window.cancelAnimationFrame(rafId);
    }, [showTaskStream, genTaskStream?.content]);

    const completedScenes = autoGenerateDraft?.completed_scenes || 0;
    const currentProjectIsEmpty = !!currentProject.is_empty;
    const canContinueAutoGenerate = !!autoGenerateDraft
        && autoGenerateDraft.stage === "failed"
        && !!String(autoGenerateDraft.current_task_id || "").trim();
    const isCurrentTaskActive = !!genTaskId && (
        genTask?.status === "pending" ||
        genTask?.status === "running" ||
        (!genTask && (autoGenerateDraft?.stage === "queued" || autoGenerateDraft?.stage === "generating"))
    );

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-3xl font-bold">剧情管理</h1>
                <div className="flex gap-2">
                    <button
                        onClick={fetchProjects}
                        disabled={loading}
                        className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-50"
                    >
                        <RotateCcw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} /> 刷新
                    </button>
                    <button
                        onClick={() => {
                            setCurrentProject({ disable_reference_images: true });
                            setIsEditing(true);
                        }}
                        className="flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md hover:bg-primary/90 transition-colors"
                    >
                        <Plus className="w-4 h-4" /> 新增项目
                    </button>
                </div>
            </div>

            <div className="bg-card border border-border rounded-lg shadow-sm overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="text-xs text-muted-foreground uppercase bg-accent/50">
                            <tr>
                                <th className="px-6 py-3">项目名称</th>
                                <th className="px-6 py-3">编号</th>
                                <th className="px-6 py-3">画风</th>
                                <th className="px-6 py-3">备注</th>
                                <th className="px-6 py-3">创建时间</th>
                                <th className="px-6 py-3 text-right">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {projects.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="px-6 py-8 text-center text-muted-foreground">
                                        暂无项目，请点击右上角新增
                                    </td>
                                </tr>
                            ) : (
                                projects.map((project) => (
                                    <tr key={project.id} className="border-b border-border hover:bg-accent/50 transition-colors group">
                                        <td className="px-6 py-4 font-medium flex items-center gap-2">
                                            <Folder className="w-4 h-4 text-blue-500" />
                                            {project.name}
                                        </td>
                                        <td className="px-6 py-4 font-mono text-xs text-muted-foreground">
                                            {project.code}
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className="bg-purple-500/10 text-purple-500 px-2 py-1 rounded-full text-xs border border-purple-500/20">
                                                {project.art_style?.name || "未知画风"}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground max-w-[200px] truncate" title={project.description}>
                                            {project.description || "-"}
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground whitespace-nowrap">
                                            {new Date(project.created_at || "").toLocaleDateString()}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex justify-end gap-2">
                                                <button
                                                    onClick={() => navigate(`/projects/${project.id}`)}
                                                    className="flex items-center gap-1 bg-secondary hover:bg-secondary/80 text-secondary-foreground px-3 py-1.5 rounded-md text-xs transition-colors"
                                                >
                                                    <Settings className="w-3 h-3" /> 管理
                                                </button>
                                                <button
                                                    onClick={() => openAutoGenerateModal(project)}
                                                    className="flex items-center gap-1 bg-amber-500/10 text-amber-600 hover:bg-amber-500/20 px-3 py-1.5 rounded-md text-xs transition-colors border border-amber-500/20"
                                                >
                                                    <Sparkles className="w-3 h-3" /> 一键剧集
                                                </button>
                                                <button
                                                    onClick={() => openImportStoryModal(project)}
                                                    className="flex items-center gap-1 bg-sky-500/10 text-sky-600 hover:bg-sky-500/20 px-3 py-1.5 rounded-md text-xs transition-colors border border-sky-500/20"
                                                >
                                                    <FileJson className="w-3 h-3" /> 导入/导出 JSON
                                                </button>
                                                <button
                                                    onClick={() => {
                                                        setCurrentProject(project);
                                                        setIsEditing(true);
                                                    }}
                                                    className="p-1.5 hover:bg-accent rounded-md text-muted-foreground hover:text-blue-400 transition-colors"
                                                    title="编辑"
                                                >
                                                    <Edit2 className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => handleDelete(project.id)}
                                                    className="p-1.5 hover:bg-accent rounded-md text-muted-foreground hover:text-destructive transition-colors"
                                                    title="删除"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => handleResetProjectContent(project)}
                                                    className="flex items-center gap-1 bg-orange-500/10 text-orange-600 hover:bg-orange-500/20 px-3 py-1.5 rounded-md text-xs transition-colors border border-orange-500/20"
                                                    title="清空项目内容并保留项目壳"
                                                >
                                                    <RotateCcw className="w-3 h-3" /> 清空内容
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Edit/Create Modal */}
            {isEditing && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-card border border-border rounded-lg p-6 w-full max-w-lg shadow-lg relative animate-in fade-in zoom-in duration-200">
                        <button
                            onClick={() => setIsEditing(false)}
                            className="absolute top-4 right-4 text-muted-foreground hover:text-foreground"
                        >
                            <X className="w-5 h-5" />
                        </button>
                        
                        <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
                            {currentProject.id ? <Edit2 className="w-5 h-5" /> : <Plus className="w-5 h-5" />}
                            {currentProject.id ? "编辑项目" : "新增项目"}
                        </h2>
                        
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    项目名称 <span className="text-red-500">*</span>
                                </label>
                                <Input
                                    value={currentProject.name || ""}
                                    onChange={e => setCurrentProject({ ...currentProject, name: e.target.value })}
                                    placeholder="例如: 剑来"
                                />
                                <p className="text-xs text-muted-foreground mt-1">请输入你要创作的项目名称。</p>
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    项目编号 <span className="text-red-500">*</span>
                                </label>
                                <Input
                                    value={currentProject.code || ""}
                                    onChange={e => setCurrentProject({ ...currentProject, code: e.target.value })}
                                    disabled={!!currentProject.id}
                                    placeholder="例如: jianlai"
                                />
                                <p className="text-xs text-muted-foreground mt-1">
                                    只允许输入英文，这里相当于会在本地目录的output目录下创建输入的项目编号的文件夹。
                                </p>
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">
                                    画风 <span className="text-red-500">*</span>
                                </label>
                                <Combobox
                                    items={styles}
                                    value={currentProject.art_style_id}
                                    onChange={(value) => setCurrentProject({ ...currentProject, art_style_id: Number(value) })}
                                    placeholder="请选择画风..."
                                    searchPlaceholder="搜索画风..."
                                    emptyText="未找到相关画风"
                                    getItemValue={(item) => item.id}
                                    getItemLabel={(item) => item.name}
                                    renderItem={(item) => (
                                        <div className="flex flex-col">
                                            <span>{item.name}</span>
                                            <span className="text-xs text-muted-foreground line-clamp-1">{item.description}</span>
                                        </div>
                                    )}
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">备注</label>
                                <Textarea
                                    value={currentProject.description || ""}
                                    onChange={e => setCurrentProject({ ...currentProject, description: e.target.value })}
                                    placeholder="项目备注信息..."
                                />
                            </div>
                        </div>

                        <div className="mt-8 flex justify-end gap-3">
                            <button
                                onClick={() => setIsEditing(false)}
                                className="px-4 py-2 rounded-md hover:bg-accent transition-colors"
                            >
                                取消
                            </button>
                            <button
                                onClick={handleSave}
                                className="flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md hover:bg-primary/90 transition-colors"
                            >
                                <Save className="w-4 h-4" /> {currentProject.id ? "保存修改" : "创建项目"}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Auto Generate Modal */}
            {isAutoGenerating && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-card border border-border rounded-lg p-6 w-full max-w-2xl shadow-lg relative animate-in fade-in zoom-in duration-200 flex flex-col max-h-[90vh]">
                        <button
                            onClick={() => {
                                if (!genLoading) {
                                    setIsAutoGenerating(false);
                                    setAutoGenerateDraft(null);
                                }
                            }}
                            disabled={genLoading}
                            className="absolute top-4 right-4 text-muted-foreground hover:text-foreground disabled:opacity-50"
                        >
                            <X className="w-5 h-5" />
                        </button>
                        
                        <div className="mb-6">
                            <h2 className="text-xl font-bold flex items-center gap-2 text-amber-600">
                                <Sparkles className="w-5 h-5" />
                                一键剧集
                            </h2>
                            <p className="text-sm text-muted-foreground mt-1">
                                LLM 会按所选模式一次性返回角色、镜头结果、首帧图提示词、视频提示词和跨集记忆，前端这里只做提交与只读查看。
                            </p>
                            {autoGenerateDraft && (
                                <div className="mt-3 rounded-md border border-amber-500/20 bg-amber-500/5 px-3 py-2 text-xs space-y-1">
                                    <p>最近一次一键剧集记录阶段：{autoGenerateDraft.stage || "draft"}</p>
                                    {autoGenerateDraft.stage === "completed" && (
                                        <p className="text-muted-foreground">
                                            最近一次生成已完成，共 {completedScenes} 镜，当前默认会继续使用下一集集数。
                                        </p>
                                    )}
                                    {completedScenes > 0 && autoGenerateDraft.stage !== "completed" && (
                                        <p className="text-muted-foreground">
                                            当前记录里已有 {completedScenes} 个镜头结果。
                                        </p>
                                    )}
                                    {autoGenerateDraft.last_error && (
                                        <div className="max-h-24 overflow-y-auto rounded border border-destructive/20 bg-destructive/5 px-2 py-1">
                                            <p className="text-destructive break-words">
                                                上次失败原因：{autoGenerateDraft.last_error}
                                            </p>
                                        </div>
                                    )}
                                    {genTaskId && (
                                        <div className="pt-2 border-t border-amber-500/10 space-y-1">
                                            <p>当前任务 ID：{genTaskId}</p>
                                            <p>
                                                当前任务状态：{genTask?.status || "pending"}
                                                {typeof genTask?.progress === "number" ? `（${genTask.progress}%）` : ""}
                                            </p>
                                            {genTask?.error && (
                                                <div className="max-h-24 overflow-y-auto rounded border border-destructive/20 bg-destructive/5 px-2 py-1">
                                                    <p className="text-destructive break-words">
                                                        任务错误：{genTask.error}
                                                    </p>
                                                </div>
                                            )}
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                        
                        <div className="space-y-6 overflow-y-auto flex-1 pr-2">
                            <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm space-y-3">
                                <div>
                                    <div className="font-medium text-foreground">一键剧集模式</div>
                                    <p className="mt-1 text-xs text-muted-foreground">
                                        先明确告诉后端走哪条提示词分支，再按你勾选的题材标签追加专属规则，避免把所有规则都塞给 LLM。
                                    </p>
                                </div>
                                <RadioGroup
                                    value={genGenerationMode}
                                    onValueChange={(value) => setGenGenerationMode(value as "narration" | "high_quality" | "storyboard")}
                                    className="gap-3"
                                    disabled={genLoading || isCurrentTaskActive}
                                >
                                    <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                                        <RadioGroupItem value="narration" className="mt-0.5" />
                                        <div>
                                            <div className="font-medium text-foreground">旁白模式</div>
                                            <p className="mt-1 text-xs text-muted-foreground">
                                                保持当前旁白驱动逻辑，适合解说式叙事和普通一键剧集生成。
                                            </p>
                                        </div>
                                    </label>
                                    <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                                        <RadioGroupItem value="high_quality" className="mt-0.5" />
                                        <div>
                                            <div className="font-medium text-foreground">高质量模式</div>
                                            <p className="mt-1 text-xs text-muted-foreground">
                                                面向小说或故事原文，按导演视角重构镜头，不依赖旁白推进剧情。
                                            </p>
                                        </div>
                                    </label>
                                    <label className="flex items-start gap-3 cursor-pointer rounded-md border border-border bg-background/70 px-3 py-3">
                                        <RadioGroupItem value="storyboard" className="mt-0.5" />
                                        <div>
                                            <div className="font-medium text-foreground">严格分镜脚本模式</div>
                                            <p className="mt-1 text-xs text-muted-foreground">
                                                面向已写好的分镜脚本或拍摄脚本，优先保留原镜头顺序、对白归属和镜头意图。
                                            </p>
                                        </div>
                                    </label>
                                </RadioGroup>
                            </div>

                            <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm space-y-3">
                                <div className="flex items-start gap-2">
                                    <Tags className="w-4 h-4 mt-0.5 text-primary" />
                                    <div>
                                        <div className="font-medium text-foreground">标签增强</div>
                                        <p className="mt-1 text-xs text-muted-foreground">
                                            可同时勾选多个标签。勾选后，对应规则会追加到本次一键剧集的 LLM 输入里。
                                        </p>
                                    </div>
                                </div>
                                {autoGenerateTags.length === 0 ? (
                                    <div className="rounded-md border border-dashed border-border bg-background/70 px-3 py-3 text-xs text-muted-foreground">
                                        还没有可选标签。你可以先去左侧「标签管理」页面维护规则。
                                    </div>
                                ) : (
                                    <div className="max-h-[260px] overflow-y-auto pr-1">
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        {autoGenerateTags.map((tag) => {
                                            const selected = genTagIds.includes(tag.id);
                                            return (
                                                <button
                                                    key={tag.id}
                                                    type="button"
                                                    onClick={() => toggleAutoGenerateTag(tag.id)}
                                                    disabled={genLoading || isCurrentTaskActive}
                                                    className={`text-left rounded-md border px-3 py-3 transition-colors ${
                                                        selected
                                                            ? "border-primary bg-primary/10"
                                                            : "border-border bg-background/70 hover:bg-accent/60"
                                                    } disabled:opacity-60`}
                                                >
                                                    <div className="font-medium text-foreground">{tag.name}</div>
                                                    <p className="mt-1 text-xs text-muted-foreground line-clamp-3">
                                                        {tag.description}
                                                    </p>
                                                </button>
                                            );
                                        })}
                                        </div>
                                    </div>
                                )}
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-2">
                                    小说 / 剧本内容 <span className="text-red-500">*</span>
                                </label>
                                <Textarea
                                    value={genPlot}
                                    onChange={e => setGenPlot(e.target.value)}
                                    placeholder="请输入本集小说内容或剧本全文，系统会一次性生成 characters 与 scenes..."
                                    className="min-h-[150px]"
                                    disabled={genLoading}
                                />
                            </div>

                            {!currentProjectIsEmpty && (
                                <div>
                                    <label className="block text-sm font-medium mb-2">
                                        生成集数
                                    </label>
                                    <Input
                                        type="number"
                                        min={1}
                                        value={genEpisode}
                                        onChange={e => setGenEpisode(Number(e.target.value))}
                                        disabled={genLoading}
                                    />
                                    <p className="mt-2 text-xs text-muted-foreground">
                                        当前项目已经有内容，默认会续到下一集。你也可以按需要改成别的目标集数。
                                    </p>
                                </div>
                            )}

                            {currentProjectIsEmpty && (
                                <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm text-muted-foreground">
                                    当前项目还是空项目，本次会直接从第 1 集开始创建。
                                </div>
                            )}

                            <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-sm">
                                <div className="font-medium text-amber-600">
                                    当前系统固定使用无参考图模式
                                </div>
                                <p className="mt-1 text-xs text-muted-foreground">
                                    一键剧集只负责生成角色与镜头文本结果，后续场景图统一直接使用 image_prompt 提交到图像工作流。
                                </p>
                            </div>

                            {autoGenerateDraft?.characters_json && (
                                <div>
                                    <label className="block text-sm font-medium mb-2">角色结果 (JSON)</label>
                                    <Textarea
                                        value={autoGenerateDraft.characters_json}
                                        className="min-h-[180px] font-mono text-xs"
                                        readOnly
                                    />
                                </div>
                            )}
                            {autoGenerateDraft?.scenes_json && (
                                <div>
                                    <label className="block text-sm font-medium mb-2">镜头结果 (JSON{completedScenes > 0 ? `，共 ${completedScenes} 镜` : ""})</label>
                                    <Textarea
                                        value={autoGenerateDraft.scenes_json}
                                        className="min-h-[220px] font-mono text-xs"
                                        readOnly
                                    />
                                </div>
                            )}
                            {autoGenerateDraft?.episode_memory_json && (
                                <div>
                                    <label className="block text-sm font-medium mb-2">跨集记忆结果 (JSON)</label>
                                    <Textarea
                                        value={autoGenerateDraft.episode_memory_json}
                                        className="min-h-[180px] font-mono text-xs"
                                        readOnly
                                    />
                                </div>
                            )}
                            {showTaskStream && (
                                <div>
                                    <label className="block text-sm font-medium mb-2">
                                        当前任务实时 LLM 流
                                        {genTaskStream?.status ? `（${genTaskStream.status}）` : ""}
                                    </label>
                                    <div
                                        ref={taskStreamRef}
                                        className="h-[320px] min-h-[320px] overflow-y-auto rounded-md border border-input bg-background px-3 py-2 font-mono text-xs whitespace-pre-wrap break-words"
                                    >
                                        {genTaskId
                                            ? (genTaskStream?.content || "正在等待当前任务返回实时流...")
                                            : "当前还没有任务流"}
                                    </div>
                                </div>
                            )}

                        </div>

                        <div className="mt-8 flex justify-end gap-3 pt-4 border-t border-border">
                            <button
                                onClick={() => {
                                    setIsAutoGenerating(false);
                                    setAutoGenerateDraft(null);
                                }}
                                disabled={genLoading}
                                className="px-4 py-2 rounded-md hover:bg-accent transition-colors disabled:opacity-50"
                            >
                                取消
                            </button>
                            <button
                                onClick={() => setShowTaskStream(prev => !prev)}
                                disabled={!genTaskId}
                                className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                            >
                                <Settings className="w-4 h-4" />
                                {showTaskStream ? "隐藏当前任务LLM流" : "查看当前任务LLM流"}
                            </button>
                            <button
                                onClick={() => navigate("/logs")}
                                disabled={genLoading}
                                className="flex items-center gap-2 bg-secondary text-secondary-foreground px-4 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                            >
                                <Settings className="w-4 h-4" />
                                全局日志
                            </button>
                            <button
                                onClick={handleAutoGenerate}
                                disabled={genLoading || isCurrentTaskActive}
                                className="flex items-center gap-2 bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors disabled:opacity-70"
                            >
                                {genLoading ? (
                                    <>
                                        <RotateCcw className="w-4 h-4 animate-spin" />
                                        AI 生成中...
                                    </>
                                ) : isCurrentTaskActive ? (
                                    <>
                                        <RotateCcw className="w-4 h-4 animate-spin" />
                                        当前任务执行中
                                    </>
                                ) : (
                                    <>
                                        <Sparkles className="w-4 h-4" />
                                        {canContinueAutoGenerate ? "继续生成" : "开始生成"}
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {isImportingStory && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-card border border-border rounded-lg p-6 w-full max-w-3xl shadow-lg relative animate-in fade-in zoom-in duration-200 flex flex-col max-h-[90vh]">
                        <button
                            onClick={() => {
                                if (!importLoading) {
                                    setIsImportingStory(false);
                                    setImportStoryJSON("");
                                }
                            }}
                            disabled={importLoading}
                            className="absolute top-4 right-4 text-muted-foreground hover:text-foreground disabled:opacity-50"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <div className="mb-6">
                            <h2 className="text-xl font-bold flex items-center gap-2 text-sky-600">
                                <FileJson className="w-5 h-5" />
                                导入 / 导出标准剧情 JSON
                            </h2>
                            <p className="text-sm text-muted-foreground mt-1">
                                这里用于导入外部 AI 已经生成好的严格 JSON，或者把当前项目某一集导出成同结构 JSON。系统会直接按现有角色锁定规则、镜头结构规则和 shots 单表结构处理，不会做后端补全或改写。
                            </p>
                        </div>

                        <div className="space-y-5 overflow-y-auto flex-1 pr-2">
                            <div>
                                <label className="block text-sm font-medium mb-2">导入集数</label>
                                <Input
                                    type="number"
                                    min={1}
                                    value={importEpisode}
                                    onChange={(e) => setImportEpisode(Number(e.target.value))}
                                    disabled={importLoading}
                                />
                                <p className="mt-2 text-xs text-muted-foreground">
                                    导入会直接写入这一集；如果该集已经存在镜头，系统会拒绝导入。
                                </p>
                            </div>

                            <div className="rounded-lg border border-border bg-secondary/20 px-4 py-3 text-xs text-muted-foreground space-y-1">
                                <p>固定要求：</p>
                                <p>1. 顶层必须包含 `total_scenes`、`characters`、`scenes`、`episode_memory`。</p>
                                <p>2. `image_prompt` 必须是 5 行：主体 / 场景 / 构图 / 光影 / 约束。</p>
                                <p>3. `video_prompt` 必须是 5 行：`Style:` / `Phase 1 (...)` / `Audio:` / `Phase 2 (...)` / `Audio:`。</p>
                                <p>4. 如果项目已有锁定角色，`characters` 里只能放新角色，旧角色不要重复返回。</p>
                                <p>5. 当前主链路不再要求返回 `dialogue`，重点放在 `narration`、`image_prompt`、`video_prompt` 与 `duration_seconds`。</p>
                                <p>6. 所有字段值必须使用简体中文；只有 `video_prompt` 的 5 个固定标签保留英文。</p>
                            </div>

                            <div className="rounded-lg border border-sky-500/20 bg-sky-500/5 px-4 py-3 text-sm">
                                <div className="font-medium text-sky-600">导出说明</div>
                                <p className="mt-1 text-xs text-muted-foreground">
                                    导出会按当前集生成标准 JSON，包含本集镜头、跨集记忆，以及本集 `episode_memory.character_status` 涉及到的角色资产；如果当前集没有命中角色状态，会回退导出当前项目全部角色资产。
                                </p>
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-2">
                                    导入 JSON <span className="text-red-500">*</span>
                                </label>
                                <Textarea
                                    value={importStoryJSON}
                                    onChange={(e) => setImportStoryJSON(e.target.value)}
                                    placeholder={`{\n  "total_scenes": 2,\n  "characters": [],\n  "scenes": [],\n  "episode_memory": {}\n}`}
                                    className="min-h-[360px] font-mono text-xs"
                                    disabled={importLoading}
                                />
                            </div>
                        </div>

                        <div className="mt-8 flex justify-end gap-3 pt-4 border-t border-border">
                            <button
                                onClick={() => {
                                    setIsImportingStory(false);
                                    setImportStoryJSON("");
                                }}
                                disabled={importLoading || exportLoading}
                                className="px-4 py-2 rounded-md hover:bg-accent transition-colors disabled:opacity-50"
                            >
                                取消
                            </button>
                            <button
                                onClick={handleExportStoryJSON}
                                disabled={importLoading || exportLoading}
                                className="flex items-center gap-2 bg-secondary text-secondary-foreground px-6 py-2 rounded-md hover:bg-secondary/80 transition-colors disabled:opacity-70"
                            >
                                {exportLoading ? (
                                    <>
                                        <RotateCcw className="w-4 h-4 animate-spin" />
                                        导出中...
                                    </>
                                ) : (
                                    <>
                                        <FileJson className="w-4 h-4" />
                                        导出当前集 JSON
                                    </>
                                )}
                            </button>
                            <button
                                onClick={handleImportStoryJSON}
                                disabled={importLoading || exportLoading}
                                className="flex items-center gap-2 bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors disabled:opacity-70"
                            >
                                {importLoading ? (
                                    <>
                                        <RotateCcw className="w-4 h-4 animate-spin" />
                                        导入中...
                                    </>
                                ) : (
                                    <>
                                        <FileJson className="w-4 h-4" />
                                        导入并入库
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
